### ISSUE TITLE
Can't use a fresh install: "Error: Cannot find module 'shelljs'"

### ISSUE THREAD

**Issue by kyle-johnson** [jaredpalmer/tsdx#263]
### Current Behavior

Command:
`npm install -g tsdx`

Output:
```
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
/Users/kylejohnson/.nvm/versions/node/v12.11.1/bin/tsdx -> /Users/kylejohnson/.nvm/versions/node/v12.11.1/lib/node_modules/tsdx/dist/index.js

> fsevents@1.2.9 install /Users/kylejohnson/.nvm/versions/node/v12.11.1/lib/node_modules/tsdx/node_modules/jest-haste-map/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download
[fsevents] Success: "/Users/kylejohnson/.nvm/versions/node/v12.11.1/lib/node_modules/tsdx/node_modules/jest-haste-map/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node" is installed via remote

> core-js@2.6.10 postinstall /Users/kylejohnson/.nvm/versions/node/v12.11.1/lib/node_modules/tsdx/node_modules/core-js
> node postinstall || echo "ignore"

npm WARN @wessberg/rollup-plugin-ts@1.1.72 requires a peer of typescript@^3.x but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.

+ tsdx@0.10.2
added 947 packages from 656 contributors in 78.13s
```

Command:
`tsdx create shared`

Output:
```
Error: Cannot find module 'shelljs'
Require stack:
- /Users/kylejohnson/.nvm/versions/node/v12.11.1/lib/node_modules/tsdx/dist/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:15)
    at Function.Module._load (internal/modules/cjs/loader.js:685:27)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/kylejohnson/.nvm/versions/node/v12.11.1/lib/node_modules/tsdx/dist/index.js:19:43)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1014:10)
```

### Expected behavior

It should work without me installing shelljs

### Additional context

Once I `npm install -g shelljs`, then `tsdx create` works

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           | 0.10.2 |
| npm         | 6.11.3 |
| Operating System | Mac OS 10.14 |

**Comment by jaredpalmer** [comment]
Thansk!
